repos:
-   repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        language: python_venv
        additional_dependencies: [flake8-comprehensions>=3.1.0]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        language: python_venv
        exclude: ^pandas/__init__\.py$|^pandas/core/api\.py$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
     -  id: mypy
        # We run mypy over all files because of:
        #  * changes in type definitions may affect non-touched files.
        #  * Running it with `mypy pandas` and the filenames will lead to
        #    spurious duplicate module errors,
        #    see also https://github.com/pre-commit/mirrors-mypy/issues/5
        pass_filenames: false
        args:
        - pandas
